POST http://localhost:9926/posts
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "title": "What is new in Harper 4.2",
  "body": "Harper 4.2 is the latest version of Harper. It has many new features and improvements.",
  "slug": "what-is-new-in-harper-4-2",
  "published": true,
  "tags": ["harper", "4.2", "new"]
}
